# Generated by Django 4.2.1 on 2023-05-18 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_customer_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='poster',
            field=models.ImageField(default='product_images/image_2.jpg', upload_to='images/product_posters'),
        ),
    ]
