# Generated by Django 4.2.1 on 2023-05-27 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_category_name_en_category_name_ru_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart_item',
            name='price',
        ),
    ]
